interface pgp-wrapper-imports {}

interface pgp-wrapper-exports {
  decrypt: func(enc: list<u8>, key: string, pass: string) -> result<list<u8>, string>
}

default world pgp-wrapper-world {
  import pgp-wrapper-imports: self.pgp-wrapper-imports
  export pgp-wrapper-exports: self.pgp-wrapper-exports
}
